### ISSUE TITLE
Error when installing v1.2.0

### ISSUE THREAD

**Issue by andytinkham** [bertholdm/isfdb3-calibre#1]
Since 1.2.0 came out, I haven't been able to install it. It gives an error when I try to install it from within Calibre.

I tried removing the 1.1.3 version I had previously installed, restarted Calibre, and tried to install cleanly - same error. 

Plugin version: 1.2.0

Error Details:
calibre, version 6.14.0
ERROR: Install plugin failed: A problem occurred while installing this plugin. This plugin will now be uninstalled. Please post the error message in details below into the forum thread for this plugin and restart calibre.

Traceback (most recent call last):
  File "calibre/gui2/dialogs/plugin_updater.py", line 710, in _install_clicked
  File "calibre/customize/ui.py", line 513, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 307, in load
  File "importlib/__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.isfdb3.__init__", line 13, in <module>
    from calibre_plugins.isfdb3.objects import Publication, Title, PublicationsList, TitleList, TitleCovers
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.isfdb3.objects", line 16, in <module>
    from .myglobals import LANGUAGES, LOCALE_LANGUAGE_CODE, LOCALE_COUNTRY, EXTERNAL_IDS, TRANSLATION_REPLACINGS
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 206, in exec_module
  File "calibre_plugins.isfdb3.myglobals", line 7, in <module>
    LOCALE_COUNTRY = LOCALE_LANGUAGE_CODE[-2:]
TypeError: 'NoneType' object is not subscriptable

**Comment by bertholdm** [comment]
Hello again,
the error seems to be caused by using locale.getdefaultlocale(). I've changed it to locale.getlocale() with fallback to 'en_US'.

**Comment by andytinkham** [comment]
Thank you! I was able to install v1.2.1 without issue!
